name: Update Formula

on:
  repository_dispatch:
    types: [update-formula] # with client_payload.packages
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: ''

jobs:
  update_formula:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1
      - name: Dart SDK
        run: dart --version
      - uses: actions/checkout@v2
      - name: Extract version
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version != ''
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - name: Extract version
        if: github.event_name == 'repository_dispatch' && github.event.client_payload.version != ''
        run: echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
      - name: Update Formula
        run: |
          export VERSION="${{ env.VERSION }}"
          echo "VERSION=$VERSION"
          SPIDER_MACOS_URL="https://github.com/BirjuVachhani/spider/releases/download/$VERSION/spider-$VERSION-macos.tar.gz"
          curl -L -o spider-$VERSION-macos.tar.gz "$SPIDER_MACOS_URL"
          export SPIDER_MACOS_SHA=`sha256sum spider-$VERSION-macos.tar.gz | cut -d' ' -f1`
          echo "MacOS SHA: $SPIDER_MACOS_SHA"
          SPIDER_LINUX_URL="https://github.com/BirjuVachhani/spider/releases/download/$VERSION/spider-$VERSION-linux-amd64.tar.gz"
          curl -L -o spider-$VERSION-linux-amd64.tar.gz "$SPIDER_LINUX_URL"
          export SPIDER_LINUX_SHA=`sha256sum spider-$VERSION-linux-amd64.tar.gz | cut -d' ' -f1`
          echo "Linux SHA: $SPIDER_LINUX_SHA"
          dart update_formula.dart "$VERSION" "$SPIDER_MACOS_SHA" "$SPIDER_LINUX_SHA"
      - name: Commit & push changes
        uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: 'Formula/spider.rb'
          message: "Bump up formula version to ${{ env.VERSION }}"